name: Microsoft Graph Toolkit New Version Released
on:
  repository_dispatch:
    types: [graph-toolkit-released]
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Get Release Detail
        id: detail
        uses: actions/github-script@v6
        with:
          script: |
            const responseBody = "<p>Microsoft Graph Toolkit v" + "${{ github.event.client_payload.version }} has been released.\n Details can be found here: https://github.com/microsoftgraph/microsoft-graph-toolkit/releases/tag/v${{ github.event.client_payload.version }}";
            return responseBody;

      - name: Setup Email and Recipient
        id: email
        run: |
          emails="vsciotadt@microsoft.com;junjieli@microsoft.com;zhshang@microsoft.com;donji@microsoft.com;zhany@microsoft.com"
          subject="Microsoft Graph Toolkit v${{ github.event.client_payload.version }} Released"

          echo "to=$emails" >> $GITHUB_OUTPUT
          echo "subject=$subject" >> $GITHUB_OUTPUT

      - name: Send E-mail Notifications
        uses: satak/webrequest-action@master
        with:
          url: https://prod-30.eastus.logic.azure.com:443/workflows/9aa865da96054bd89749c2d4ce68df8e/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uIoB06NUHSnKoZeWjNDI9t4rrhbTBKxJNiBtDoMRSQs
          method: POST
          payload: |
            {
              "to": "${{ steps.email.outputs.to }}",
              "body": ${{ steps.detail.outputs.result }},
              "subject": "${{ steps.email.outputs.subject }}",
              "apiKey": "${{ secrets.MAIL_API_KEY }}"
            }
