name: milestoned-azdo

on: 
  issues:
    types: [milestoned]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: "devdiv-azure-service-dmitryr/teamsfx-issue-triage-bot"
          ref: main
          path: ./actions
          token: ${{secrets.GHEC_BOT_PAT}}
      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Create AZDO Item 
        uses: ./actions/milestoned
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          milestone-prefix: "CY"
          devops-token: ${{secrets.ADO_PAT}}
          devops-org: "msazure"
          devops-projectId: "Microsoft Teams Extensibility"
          title-prefix: "[Github]"
          bug-label: "bug"
          bug-area-path: "Microsoft Teams Extensibility"
          bug-iteration-path: "Microsoft Teams Extensibility"