name: SDK CI

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/sdk/**
  workflow_dispatch:

jobs:
  build-and-test-on-latest-version:
    name: Test SDK on (${{ matrix.os }} with node ${{ matrix.node-version }})

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup project
        run: |
          npm run setup

      # https://github.com/ryanclark/karma-webpack/issues/494
      - name: Windows temp dir fix
        if: matrix.os == 'windows-latest'
        run: |
          echo TEMP="D:\Temp" >> $env:GITHUB_ENV
          echo TMP="D:\Temp" >> $env:GITHUB_ENV

      - name: Remove package-lock(Windows)
        if: matrix.os == 'windows-latest'
        uses: JesseTG/rm@v1.0.0
        with:
          path: packages\sdk\package-lock.json

      - name: Remove package-lock(Linux)
        if: matrix.os != 'windows-latest'
        run: |
          rm packages/sdk/package-lock.json

      - name: Setup project
        run: |
          npm install
        working-directory: ./packages/sdk

      - name: Unit Test
        run: |
          npm run test:unit
        working-directory: ./packages/sdk
