name: SimpleAuth CI

on:
  push:
    paths:
      - "packages/simpleauth/**"
    branches: [main]
  pull_request:
    paths:
      - "packages/simpleauth/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/simpleauth/

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet build -c Release -p:WebDriverPlatform=linux64 Microsoft.TeamsFx.SimpleAuth.sln
      - name: Test
        env:
          TEAMS_SIMPLE_AUTH_IntegrationTestSettings__AdminClientId: ${{secrets.SIMPLE_AUTH_TEST_ADMIN_CLIENT_ID}}
          TEAMS_SIMPLE_AUTH_IntegrationTestSettings__AdminClientSecret: ${{secrets.SIMPLE_AUTH_TEST_ADMIN_CLIENT_SECRET}}
          TEAMS_SIMPLE_AUTH_IntegrationTestSettings__TenantId: ${{secrets.SIMPLE_AUTH_TEST_TENANT_ID}}
          TEAMS_SIMPLE_AUTH_IntegrationTestSettings__TestUserName: ${{secrets.SIMPLE_AUTH_TEST_USER_NAME}}
          TEAMS_SIMPLE_AUTH_IntegrationTestSettings__TestPassword: ${{secrets.SIMPLE_AUTH_TEST_PASSWORD}}
          TEAMS_SIMPLE_AUTH_IntegrationTestSettings__TestUserName2: ${{secrets.SIMPLE_AUTH_TEST_USER_NAME_2}}
          TEAMS_SIMPLE_AUTH_IntegrationTestSettings__TestPassword2: ${{secrets.SIMPLE_AUTH_TEST_PASSWORD_2}}
        run: dotnet test Microsoft.TeamsFx.SimpleAuth.sln --filter TestCategory="P0"
